name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    name: 🔄 Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Update dependencies
        run: |
          npm update
          npm audit fix --force

      - name: Run tests
        run: |
          npm ci
          npm run test:ci

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: '🔄 Automated dependency updates'
          body: |
            ## 🔄 Automated Dependency Updates

            This PR contains automated dependency updates.

            ### Changes:
            - Updated npm dependencies to latest versions
            - Applied security fixes via `npm audit fix`

            ### Testing:
            - ✅ All tests pass
            - ✅ Security audit clean

            Please review the changes and merge if everything looks good.
          branch: chore/dependency-updates
          delete-branch: true
